name: statsmod
version: '1.0'
main: xyz.squables.statsmod.Statsmod
api-version: '1.21'
commands:
  statsmod:
    description: Statsmod stuff
    usage: /statsmod
    aliases: [ sm ]
    permission: stats.statsmod
    permission-message: you cannot do that